language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  # - clang

env:
  global:
    - secure: ${GH_PERSONAL_ACCESS_TOKEN}
    - ITK_TAG: v4.13.2
    - ZIP_NAME: itk_${ITK_TAG}_${TRAVIS_OS_NAME}_${TRAVIS_COMPILER}

install:
  - cd ${TRAVIS_BUILD_DIR}
  - git clone -b ${ITK_TAG} https://github.com/InsightSoftwareConsortium/ITK.git

script:
  - cd ${TRAVIS_BUILD_DIR}/ITK
  - cmake . -Bbin -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/install -DBUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF -DModule_ITK_VtkGlue=ON -DINSTALL_GTEST=OFF -DITK_DOXYGEN_HTML=OFF
  - cd ${TRAVIS_BUILD_DIR}/ITK/bin
  - cmake --build . --config RELEASE
  - cmake --build . --config RELEASE --target install

after_success:
  - cd ${TRAVIS_BUILD_DIR}/install
  - zip -r ${ZIP_NAME}.zip * # zip
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir deployment
  - cp install/${ZIP_NAME}.zip deployment/${ZIP_NAME}.zip

deploy:
  provider: releases # GitHub
  name: itk_${ITK_TAG}
  api_key:
    secure: ${GH_PERSONAL_ACCESS_TOKEN}
  file_glob: ON # to use wildcards
  file: deployment/*
  skip_cleanup: ON
  on:
    tags: true
