language: cpp
dist: trusty

os:
  - linux
  - osx

compiler:
  - gcc
  # - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9

env:
  matrix:
    - CXX_STANDARD=98
    # - CXX_STANDARD=11
  global:
    - secure: ${GH_PERSONAL_ACCESS_TOKEN}
    - ITK_TAG: v4.12.0

install:
  - cd ${TRAVIS_BUILD_DIR}
  - git clone -b ${ITK_TAG} https://github.com/InsightSoftwareConsortium/ITK.git

script:
  - cd ${TRAVIS_BUILD_DIR}/ITK
  - cmake . -Bbin -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/install -DBUILD_EXAMPLES=OFF -DBUILD_TESTING=OFF -DModule_ITK_VtkGlue=ON -DINSTALL_GTEST=OFF -DITK_DOXYGEN_HTML=OFF -DCXX_STANDARD_REQUIRED=ON -DCMAKE_CXX_STANDARD=${CXX_STANDARD}
  - cd ${TRAVIS_BUILD_DIR}/ITK/bin
  - cmake --build . --config RELEASE
  - cmake --build . --config RELEASE --target install

after_success:
  - export ZIP_NAME=itk_${ITK_TAG}_${TRAVIS_OS_NAME}_${CXX}_CXX${CXX_STANDARD}
  - cd ${TRAVIS_BUILD_DIR}/install
  - zip -r ${ZIP_NAME}.zip * # zip
  - cd ${TRAVIS_BUILD_DIR}
  - mkdir deployment
  - cp install/${ZIP_NAME}.zip deployment/${ZIP_NAME}.zip

deploy:
  provider: releases # GitHub
  name: itk_${ITK_TAG}
  api_key:
    secure: ${GH_PERSONAL_ACCESS_TOKEN}
  file_glob: ON # to use wildcards
  file: deployment/*
  skip_cleanup: ON
  on:
    tags: true
